import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Política de privacidad | La Familia Etapeya',
  description: 'Información sobre privacidad, cookies, compras digitales y publicidad en familiaetapeya.com.',
  alternates: { canonical: '/privacidad/' },
};

export default function PrivacidadPage() {
  return <main className="content-page"><nav className="shell content-nav"><a className="brand" href="/"><span>LA FAMILIA</span><strong>ETAPEYA</strong></a><a href="/">← Volver al inicio</a></nav><article className="content-wrap"><span className="eyebrow">INFORMACIÓN LEGAL</span><h1>Política de privacidad</h1><p>Última actualización: 24 de septiembre de 2026.</p><p>La Familia Etapeya utiliza este sitio para presentar productos digitales y compartir contenido para madres, padres y cuidadores. Procuramos recopilar únicamente la información necesaria para atender consultas, procesar compras y mejorar la experiencia del sitio.</p><h2>Información que podemos recibir</h2><ul><li>Datos que envías voluntariamente al comunicarte con nosotros.</li><li>Información necesaria para una compra, procesada por la plataforma de pago que se indique en el checkout.</li><li>Datos técnicos generales, como páginas visitadas, tipo de dispositivo y origen de la visita, cuando las herramientas de análisis estén activas.</li></ul><h2>Pagos y descargas</h2><p>Los pagos no se procesan directamente en familiaetapeya.com. El proveedor de comercio digital mostrará sus propias condiciones y política de privacidad antes de completar la compra. La entrega de los archivos se realizará mediante ese proveedor.</p><h2>Cookies, medición y publicidad</h2><p>El sitio podrá utilizar cookies o tecnologías similares para recordar preferencias, medir visitas y mostrar publicidad. Cuando sea legalmente necesario, se solicitará consentimiento antes de activar cookies no esenciales. Si se habilita Google AdSense, Google y sus socios podrán usar cookies para publicar y medir anuncios conforme a sus propias políticas.</p><h2>Contenido para familias</h2><p>Los productos están dirigidos a adultos responsables que buscan actividades para compartir con niños. No solicitamos intencionalmente a menores que proporcionen datos personales ni que realicen compras.</p><h2>Tus opciones</h2><p>Puedes rechazar cookies no esenciales cuando el aviso correspondiente esté disponible y puedes solicitar información sobre tus datos o pedir su eliminación contactándonos mediante nuestra página oficial de Facebook.</p><h2>Contacto</h2><p>Para consultas sobre privacidad, visita <a href="https://www.facebook.com/Lafamiliaetapeya" target="_blank" rel="noreferrer">La Familia Etapeya en Facebook</a>.</p><div className="content-footer"><a href="/">Inicio</a><a href="/consejos/">Consejos para familias</a><a href="/terminos/">Términos de uso</a></div></article></main>;
}
