import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Términos de uso y compra | La Familia Etapeya',
  description: 'Condiciones aplicables a los productos digitales de La Familia Etapeya.',
  alternates: { canonical: '/terminos/' },
};

export default function TerminosPage() {
  return <main className="content-page"><nav className="shell content-nav"><a className="brand" href="/"><span>LA FAMILIA</span><strong>ETAPEYA</strong></a><a href="/">← Volver al inicio</a></nav><article className="content-wrap"><span className="eyebrow">INFORMACIÓN LEGAL</span><h1>Términos de uso y compra</h1><p>Última actualización: 24 de septiembre de 2026.</p><h2>Productos digitales</h2><p>Los packs de La Familia Etapeya son archivos digitales. No se enviará un producto físico. Antes de comprar, revisa la descripción del pack, sus archivos incluidos y los requisitos de impresión.</p><h2>Licencia familiar</h2><p>La compra concede una licencia personal y no transferible para utilizar e imprimir los materiales dentro del hogar del comprador. No está permitido revender, compartir públicamente, subir a otros sitios, modificar para comercializar ni distribuir los archivos originales.</p><h2>Precios y pagos</h2><p>El precio vigente aparece junto a cada producto y se confirma en la página de pago. El proveedor de comercio digital procesa el cobro, la entrega y los comprobantes. Cualquier impuesto o cargo aplicable se mostrará en el checkout.</p><h2>Descargas y soporte</h2><p>Después de aprobarse el pago, el comprador recibirá las instrucciones de descarga en el correo utilizado durante la compra. Si existe un problema técnico, deberá comunicarse con nosotros indicando el correo de compra y el nombre del producto, sin enviar datos de tarjeta ni contraseñas.</p><h2>Reembolsos</h2><p>Los reembolsos se gestionan de acuerdo con la legislación aplicable y las condiciones del proveedor de pago. Si un archivo no puede descargarse o está dañado, intentaremos resolver la entrega antes de evaluar otras soluciones.</p><h2>Propiedad intelectual</h2><p>Los nombres, diseños, fotografías, personajes y materiales de La Familia Etapeya pertenecen a sus respectivos titulares. La compra no transfiere derechos de autor ni autoriza usos comerciales.</p><h2>Contacto</h2><p>Para soporte, visita <a href="https://www.facebook.com/Lafamiliaetapeya" target="_blank" rel="noreferrer">La Familia Etapeya en Facebook</a>.</p><div className="content-footer"><a href="/">Inicio</a><a href="/consejos/">Consejos para familias</a><a href="/privacidad/">Política de privacidad</a></div></article></main>;
}
