const messenger = "https://m.me/Lafamiliaetapeya";
const products = [
  {number:"01",title:"Aventuras para colorear",price:"$1",image:"/images/pack-01.jpg",tone:"blue",tag:"Para empezar",items:["10 láminas familiares","13 páginas listas para imprimir","Descarga digital en PDF"],cta:"Comprar por $1",href:"https://payhip.com/b/cx69d"},
  {number:"02",title:"Color, risas y cómic",price:"$2",image:"/images/pack-02.jpg",tone:"coral",tag:"El favorito",items:["Todo el Pack 01","Cómic El Masaje Extremo","26 páginas de diversión"],cta:"Comprar por $2",href:"https://payhip.com/b/3H19Y"},
  {number:"03",title:"Mega Pack Etapeya",price:"$3",image:"/images/mega-pack.jpg",tone:"navy",tag:"Mejor valor",items:["86 páginas imprimibles","Cómic + sopas + retos + juego","Soluciones y diploma final"],cta:"Llevarme todo por $3",href:"https://payhip.com/b/OsztW"},
];

export default function Home(){return <main>
  <nav className="nav shell"><a className="brand" href="#inicio" aria-label="La Familia Etapeya, inicio"><span>LA FAMILIA</span><strong>ETAPEYA</strong></a><div className="navlinks"><a href="#packs">Los packs</a><a href="#incluye">Qué incluye</a><a href="#familia">La familia</a><a href="#preguntas">Preguntas</a></div><a className="button button-small" href="#packs">Ver ofertas</a></nav>

  <section id="inicio" className="hero shell"><div className="hero-copy"><span className="eyebrow">JUEGOS QUE UNEN A LA FAMILIA</span><h1>Menos pantalla.<br/><em>Más aventuras juntos.</em></h1><p>Actividades imprimibles, un cómic lleno de risas y un juego de mesa para convertir cualquier tarde en un recuerdo Etapeya.</p><div className="hero-actions"><a className="button" href="#packs">Elegir mi pack <span>→</span></a><a className="text-link" href="#como-funciona">¿Cómo funciona?</a></div><div className="trust"><b>✓ Descarga digital</b><b>✓ Imprime en casa</b><b>✓ Juega hoy</b></div></div><div className="hero-visual"><div className="sun"/><img src="/images/familia-real-hero-v2.png" alt="Los cinco integrantes reales de La Familia Etapeya coloreando, leyendo y jugando juntos"/><span className="sticker sticker-one">¡86 páginas!</span><span className="sticker sticker-two">Desde $1</span></div></section>

  <section className="marquee" aria-label="Beneficios"><div>COLOREA ✦ RÍE ✦ PIENSA ✦ LEE ✦ JUEGA ✦ COMPARTE ✦ COLOREA ✦ RÍE ✦ PIENSA ✦ LEE ✦ JUEGA ✦</div></section>

  <section id="packs" className="packs-section"><div className="shell section-heading"><span className="eyebrow">ELIGE TU AVENTURA</span><h2>Un pack para cada momento</h2><p>Empieza con las láminas o llévate el universo completo. Un solo pago, sin suscripciones.</p></div><div className="shell product-grid">{products.map(p=><article className={`product-card ${p.tone}`} key={p.number}><div className="product-image"><span className="product-tag">{p.tag}</span><img src={p.image} alt={`Portada de ${p.title}`}/></div><div className="product-body"><span className="product-number">PACK {p.number}</span><div className="title-price"><h3>{p.title}</h3><strong>{p.price}</strong></div><ul>{p.items.map(item=><li key={item}>✓ {item}</li>)}</ul><a className="product-cta" href={p.href} target="_blank" rel="noreferrer">{p.cta} <span>→</span></a></div></article>)}</div><p className="purchase-note">Pago protegido mediante Payhip y PayPal · Descarga automática e inmediata después de la compra.</p></section>

  <section id="incluye" className="inside-section"><div className="shell split-heading"><div><span className="eyebrow light">DENTRO DEL MEGA PACK</span><h2>Todo un mundo<br/>para descubrir</h2></div><p>Una colección creada para reír, crear, pensar y jugar juntos. Cada sección tiene su propia aventura.</p></div><div className="shell gallery-grid"><article className="gallery-card wide"><img src="/images/comic-portada.jpg" alt="Portada del cómic El Masaje Extremo"/><div><span>01 · LEE</span><h3>El Masaje Extremo</h3><p>Un fotocómic familiar completo, lleno de travesuras y con un final inolvidable.</p></div></article><article className="gallery-card"><img src="/images/actividad-colorear.png" alt="Familia coloreando"/><div><span>02 · CREA</span><h3>10 láminas</h3></div></article><article className="gallery-card"><img src="/images/retos-ingenio.png" alt="Familia resolviendo retos"/><div><span>03 · PIENSA</span><h3>Retos de ingenio</h3></div></article><article className="gallery-card"><img src="/images/juego-mesa.png" alt="Familia jugando un juego de mesa"/><div><span>04 · JUEGA</span><h3>Aventura Etapeya</h3></div></article><article className="gallery-card diploma-card"><img src="/images/diploma.png" alt="Diploma Etapeya"/><div><span>05 · CELEBRA</span><h3>Diploma final</h3></div></article></div></section>

  <section id="como-funciona" className="steps-section"><div className="shell section-heading"><span className="eyebrow">TAN FÁCIL COMO 1, 2, 3</span><h2>De tu celular a la mesa</h2></div><div className="shell steps"><article><b>1</b><h3>Elige tu pack</h3><p>Escoge el nivel de aventura ideal para tu familia.</p></article><article><b>2</b><h3>Paga con seguridad</h3><p>Completa el pago mediante Payhip y PayPal.</p></article><article><b>3</b><h3>Descarga e imprime</h3><p>Recibe el enlace automáticamente y comienza la diversión el mismo día.</p></article></div><div className="center"><a className="button" href="#packs">Ver los 3 packs <span>→</span></a></div></section>

  <section className="video-banner"><div className="shell video-wrap"><div className="play">★</div><div><span className="eyebrow light">EL MEJOR VALOR</span><h2>86 páginas en una sola descarga</h2><p>Colorea, lee, resuelve desafíos, juega y celebra con el diploma final. Todo el universo Etapeya listo para imprimir por solo $3.</p></div><a className="button yellow-button" href="https://payhip.com/b/OsztW" target="_blank" rel="noreferrer">Comprar el Mega Pack</a></div></section>

  <section id="familia" className="family-section"><div className="shell family-layout"><div><span className="eyebrow">CONÓCENOS</span><h2>Una familia real.<br/>Risas muy reales.</h2><p>Somos La Familia Etapeya: convertimos nuestras ocurrencias, personajes y momentos cotidianos en historias para compartir. Ahora queremos llevar esa energía a tu mesa.</p><div className="socials"><a href="https://www.youtube.com/channel/UCLrgydbH_QMEWp7jK2DybPg/" target="_blank" rel="noreferrer">YouTube ↗</a><a href="https://www.tiktok.com/@netwheelsreaccionatiktok" target="_blank" rel="noreferrer">TikTok ↗</a><a href="https://www.facebook.com/Lafamiliaetapeya" target="_blank" rel="noreferrer">Facebook ↗</a></div></div><div className="family-avatars">{[["/images/mama.png","Mamá Putuza"],["/images/papa.png","Papá Pituzo"],["/images/aisha.png","Aisha"],["/images/sahir.png","Sahir"],["/images/pituzo.png","Pituzo"]].map(([src,name])=><figure key={name}><img src={src} alt={name}/><figcaption>{name}</figcaption></figure>)}</div></div></section>

  <section id="preguntas" className="faq-section"><div className="shell faq-layout"><div><span className="eyebrow">ANTES DE EMPEZAR</span><h2>Preguntas de las familias</h2><p>Todo lo que necesitas saber para comenzar tu aventura Etapeya.</p><a className="text-link" href={messenger} target="_blank" rel="noreferrer">¿Tienes otra pregunta? Escríbenos →</a></div><div className="faqs">{[["¿Es un producto físico?","No. Recibirás archivos digitales en PDF listos para descargar e imprimir en casa."],["¿Qué tamaño de hoja debo usar?","Todos los productos están preparados en tamaño A4. Imprime al 100 % para conservar las proporciones."],["¿Puedo imprimirlo más de una vez?","Sí, puedes volver a imprimir las actividades para uso de tu familia."],["¿El pago es seguro?","Sí. La compra se completa en Payhip y el cobro se procesa mediante PayPal. La Familia Etapeya no recibe ni almacena los datos de tu tarjeta."],["¿Cómo recibo mi compra?","Después de aprobarse el pago, Payhip muestra la página de descarga y también envía el enlace al correo utilizado en la compra."]].map(([q,a])=><details key={q}><summary>{q}<span>＋</span></summary><p>{a}</p></details>)}</div></div></section>

  <section className="final-cta"><div className="shell"><span className="eyebrow light">LA AVENTURA COMIENZA HOY</span><h2>¿Listos para crear<br/>un recuerdo juntos?</h2><p>Elige tu pack, imprime y deja que comiencen las risas.</p><a className="button yellow-button" href="#packs">Sí, quiero elegir mi pack <span>→</span></a></div></section>
  <footer><div className="shell footer-grid"><a className="brand" href="#inicio"><span>LA FAMILIA</span><strong>ETAPEYA</strong></a><p>Actividades, historias y juegos para disfrutar en familia.</p><div><a href="/consejos/">Consejos</a><a href="/privacidad/">Privacidad</a><a href="/terminos/">Términos</a><a href="https://www.youtube.com/channel/UCLrgydbH_QMEWp7jK2DybPg/" target="_blank" rel="noreferrer">YouTube</a><a href="https://www.tiktok.com/@netwheelsreaccionatiktok" target="_blank" rel="noreferrer">TikTok</a><a href="https://www.facebook.com/Lafamiliaetapeya" target="_blank" rel="noreferrer">Facebook</a></div></div><div className="shell copyright">© 2026 La Familia Etapeya · Producto digital para uso familiar</div></footer>
  <a className="mobile-buy" href="#packs">Ver packs desde $1 <span>→</span></a>
</main>}
